name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@master
      - name: 💚 Use Node.js ${{ matrix.node-version }}
        uses: actions/checkout@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: 🧱 Install Dependencies
        run: npm ci
      - name: 📦 Bundle Application
        run: npm run package
      - name: 🧪 Run Tests
        if: ${{ matrix.os != 'macOS-latest'}}
        uses: coactions/setup-xvfb@v1
        with:
          run: npm run wdio
      - name: 📦 Publish to GitHub releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run publish